trigger: none

variables:
- name: vmImageName
  value: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
- stage: build
  displayName: Continous Integration
  jobs:
  - job: thycotics_devops_vault
    displayName: Thycotics DevOps Vault
    steps:
    - task: ThycoticDSV@0
      displayName: Retrieving secret from Thycotics DevOps Vault
      inputs:
        ServerUrl: 'https://inchworks.secretsvaultcloud.com/v1/'
        ClientId: '785b3d11-d7ea-4bcb-befc-e4e2d901f9f7'
        ClientSecret: 'VkAHCYkQ_fKKaHuiJQQ-RC4LBUA9PEne9AaymtbgZBs'
        SecretPath: 'servers:us-east:server01'
        DataFilter: '*'
    - script: echo 'Password:' $(DSV_password)
      displayName: Secret Values