trigger: none

resources:
  pipelines:
  - pipeline: corporate-website-build
    project: Marketing
    source: corporate-website-build
    trigger: none
    # trigger:
    #   branches:
    #     include:
    #     - main

variables:
- group: corporate-website-prd # Generic environment variables
- name: workload
  value: 'corporate-website'
- name: ciPipeline
  value: 'corporate-website-build'
- name: bicepFile
  value: main.bicep

extends:
  template: deploy.yml
  parameters:
    azureServiceConnection: $(azureServiceConnection)
    subscription: $(subscription)
    location: $(location)
    environment: $(environment)
    workload: ${{ variables.workload }}
    ciPipeline:  ${{ variables.ciPipeline }}
    bicepFile: ${{ variables.bicepFile }}
