# Name of the Pipeline
name: corporate-website-build
# Triggers
on: 
  push:
    branches:
     - main
# Variables
env:
  APP_DIRECTORY: app
  INFRASTRUCTURE_DIRECTORY: infrastructure
# Jobs
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [16.x]
    steps: 
    - name: Checking out source code
      uses: actions/checkout@v3
    - name: Setup node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ env.APP_DIRECTORY }}/package-lock.json
    - name: Installing dependencies
      run: npm install
      working-directory: ${{ env.APP_DIRECTORY }}
    - name: Building artifacts
      run: npm run build
      working-directory: ${{ env.APP_DIRECTORY }}
    - name: Running unit tests
      run: npm test
      working-directory: ${{ env.APP_DIRECTORY }}
    - name: Generating test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test report
        path: app/junit.xml
        reporter: jest-junit
        list-tests: 'all'
        fail-on-error: 'true'
    - name: Generating code coverage report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: app/coverage/cobertura-coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Uploading app directory
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.APP_DIRECTORY }}
        path: | 
              ${{ env.APP_DIRECTORY }}
              !${{ env.APP_DIRECTORY }}/node_modules/*
              !${{ env.APP_DIRECTORY }}/build/*
              !${{ env.APP_DIRECTORY }}/coverage/*
    - name: Uploading infra directory
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        path: ${{ env.INFRASTRUCTURE_DIRECTORY }}