name: corporate-website-deploy
on:
  workflow_call:
    inputs:
      subscription:
        required: true
        description: Azure subscription for deployment.
        type: string
      template_file_path:
        required: true
        description: Path to bicep template to deploy infrastructure.
        type: string
      package:
        required: true
        description: Artifact path to deploy on webapp
        type: string
      slot_name:
        required: false
        description: Web app slot to deploy the Artifact
        type: string
        default: production
      build_id:
        required: true
        description: Run ID to download artifact from workflow
        type: string
      workload:
        required: true
        description: Busineed workload type
        type: string
      environment:
        required: true
        description: Environment to run this workflow
        type: string
      location:
        required: true
        description: Azure location to carry out deployment
        type: string
      instance_count:
        required: true
        description: Two digit instance count for azure resources
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Downloading artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          run_id: ${{ inputs.build_id }}
      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Running preflight validation
        uses: azure/arm-deploy@v1
        with:
          #subscriptionId: ${{ inputs.subscription }}
          resourceGroupName: rg-${{ inputs.workload }}-${{ inputs.environment }}-${{ inputs.location }}-${{ inputs.instance_count }}
          template: ${{ inputs.template_file_path }}
          deploymentmode: Validate
          scope: resourcegroup
      - name: Deploying azure infrastructure
        uses: azure/arm-deploy@v1
        with:
          #subscriptionId: ${{ inputs.subscription }}
          resourceGroupName: rg-${{ inputs.workload }}-${{ inputs.environment }}-${{ inputs.location }}-${{ inputs.instance_count }}
          template: ${{ inputs.template_file_path }}
          deploymentmode: Incremental
          scope: resourcegroup
      - name: Publishing code to webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-${{ inputs.workload }}-${{ inputs.environment }}-${{ inputs.location }}-${{ inputs.instance_count }}
          package: ${{ inputs.package }}
          slot-name: ${{ inputs.slot_name }}