name: corporate-website-development
on:
  workflow_run:
    workflows: ["corporate-website-build"]
    types: [completed]
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      build_id:
        description: build workflow id to pick artifacts and deploy
        required: true
jobs:
  deploy:
    uses: inchworksinc/corporate-website/.github/workflows/deploy.yml@main
    with: 
      subscription: Sandbox
      template_file_path: infrastructure/main.bicep
      package: app
      slot_name: production
      build_id: ${{ inputs.build_id }}
      workload: corporate-website
      environment: dev
      location: eastus2
      instance_count: 01
    secrets: inherit