name: corporate-website-staging
on:
  workflow_dispatch:
    inputs:
      build_id:
        description: build workflow id to pick artifacts and deploy
        required: true
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    uses: fbitn/corporate-website/.github/workflows/deploy.yml@main
    with: 
      subscription: Sandbox
      template_file_path: infrastructure/main.bicep
      build_id: ${{ inputs.build_id }}
      workload: corporate-website
      environment: uat
      location: eastus2
      instance_count: "01"
    secrets: inherit
    